cmus status in tmux

diff --git a/stowed-files/cmus/.local/bin/cmus-album-background b/stowed-files/cmus/.local/bin/cmus-album-background
--- a/stowed-files/cmus/.local/bin/cmus-album-background
+++ b/stowed-files/cmus/.local/bin/cmus-album-background
@@ -1,46 +1,61 @@
-#!/bin/bash
-PREVIOUS_FOLDER_PATH="/tmp/album-folder-path.txt"
-TMP_ART_PATH="/tmp/album-bg-blurred.png"
-DEFAULT_BG="#222222"
+#!/usr/bin/env bash
+#
+# Generate desktop background from currently playing album
 
-CMUS_STATUS=$(cmus-remote -Q 2>/dev/null)
-if [[ $? != 0 ]]; then
-  echo 'cmus not running, exiting'
-  hsetroot -solid "$DEFAULT_BG"
-  rm -rf "$TMP_ART_PATH" "$PREVIOUS_FOLDER_PATH"
-  exit 1
-fi
+set -euo pipefail
+IFS=$'\n\t'
 
-if grep -iq "^status stopped" <<< "$CMUS_STATUS"; then
-  echo 'cmus stopped, exiting'
-  hsetroot -solid "$DEFAULT_BG"
-  rm -rf "$TMP_ART_PATH" "$PREVIOUS_FOLDER_PATH"
-  exit 1
-fi
+default_bg="#222222"
+tmp_art_path="/tmp/cmus-album-bg-blurred.png"
+previous_folder_path="/tmp/cmus-album-folder-path.txt"
 
-ALBUM_DIRPATH=$(grep -i "^file" <<< "$CMUS_STATUS" | cut -f2- -d' ' | xargs -0 dirname)
-PREVIOUS_DIRPATH=$(cat "$PREVIOUS_FOLDER_PATH" 2>/dev/null || true)
+clear_background() {
+  hsetroot -solid "${default_bg}"
+  rm -rf "${tmp_art_path}" "${previous_folder_path}"
+}
 
-if [[ "$ALBUM_DIRPATH" != "$PREVIOUS_DIRPATH" ]]; then
-  ART_PATH=$(ls "$ALBUM_DIRPATH"/folder.* 2> /dev/null | head -n 1)
-
-  if [[ $? != 0 ]] || [[ -z "$ART_PATH" ]]; then
-    echo 'album art file not found, exiting'
-    hsetroot -solid "$DEFAULT_BG"
-    rm -rf "$TMP_ART_PATH"
-    exit 1
+main() {
+  if ! command_exists cmus-remote || ! command_exists hsetroot || ! command_exists feh; then
+    echo 'Missing requirements, exiting'
+    return 1
   fi
 
-  RESOLUTION=$(xrandr | grep \* | awk '{print $1}' | head -n 1)
-  convert "$ART_PATH" -background "$DEFAULT_BG" \
-    -scale "$RESOLUTION"\^ -paint 6 \
-    -modulate 100,20,100 -fill "$DEFAULT_BG" -colorize 20% \
-    "$TMP_ART_PATH"
+  if [[ ! -f /tmp/cmus-status.txt ]]; then
+    echo "No cmus status file found"
+    return
+  fi
 
-  echo "setting background to $TMP_ART_PATH"
-  feh --bg-center "$TMP_ART_PATH"
-else
-  echo 'already set to current album'
-fi
+  local status="$(sed -n 1p /tmp/cmus-status.txt)"
+  if [[ "${status}" == "stopped" ]]; then
+    echo 'cmus stopped, removing background'
+    clear_background
+    return
+  fi
 
-echo "$ALBUM_DIRPATH" > /tmp/album-folder-path.txt
+  local album_dirpath="$(sed -n 7p /tmp/cmus-status.txt | xargs -0 dirname)"
+  local previous_dirpath="$(cat "${previous_folder_path}" 2>/dev/null || true)"
+  echo "${album_dirpath}" > /tmp/cmus-album-folder-path.txt
+
+  if [[ "${album_dirpath}" == "${previous_dirpath}" ]]; then
+    echo 'already set to current album'
+    return
+  fi
+
+  local art_path=$(ls "${album_dirpath}"/folder.* 2> /dev/null | head -n 1)
+  if [[ $? != 0 ]] || [[ -z "${art_path}" ]]; then
+    echo "album art file not found in ${album_dirpath}, exiting"
+    clear_background
+    return
+  fi
+
+  local resolution="$(xrandr | grep \* | awk '{print $1}' | head -n 1)"
+  convert "${art_path}" -background "${default_bg}" \
+    -scale "${resolution}"\^ -paint 6 \
+    -modulate 100,20,100 -fill "${default_bg}" -colorize 20% \
+    "${tmp_art_path}"
+
+  echo "setting background to ${tmp_art_path}"
+  feh --bg-center "${tmp_art_path}"
+}
+
+main "${@}"
